In [15]:
import numpy

tmp = numpy.arange(1, 10)

x = numpy.reshape(tmp, (3, 3))
print(x)

numpy.take(x, [[1], [1]], mode='wrap')

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2],
       [2]])

In [9]:
import numpy
a = numpy.array([-1, 2, -9])
b = numpy.array([0, 1, 3])
ab = numpy.array([a, b])
# numpy.min(numpy.array([a, b]))
numpy.sum(numpy.min(numpy.array([a, b]), axis=0))

-9

In [11]:
type(numpy.where(ab < 1))

tuple

In [3]:
import numpy
a = numpy.array([[0, 1], [0, 2], [0, 3], [0, 4]])

for i in range(0, a.shape[0], 2):
    print(a[i:i+2])

[[0 1]
 [0 2]]
[[0 3]
 [0 4]]
